from __future__ import annotations

LANES: dict[str, dict[str, object]] = {
    "price_discrepancy": {"name":"Price discrepancy / arbitrage","required":["market_quotes","executable_depth"]},
    "carry": {"name":"Carry / basis / funding","required":["market_quotes","funding_or_basis","executable_depth"]},
    "yield": {"name":"Yield / staking / lending","required":["yield_rate","capacity","exit_liquidity"],"downstream":["protocol-loss statistical calibration","realized-yield forward cohort"]},
    "liquidity_provision": {"name":"Liquidity provision / market making","required":["order_book","trade_flow"],"downstream":["empirical maker queue/fill outcomes"]},
    "trend_momentum": {"name":"Directional trend / momentum","required":["market_history","execution_costs"]},
    "mean_reversion": {"name":"Mean reversion / reversal","required":["market_history","execution_costs"]},
    "fundamental_onchain": {"name":"On-chain / fundamental factor alpha","required":["chain_activity","protocol_fundamentals"]},
    "cross_sectional_relative_value": {"name":"Cross-sectional / statistical relative value","required":["multi_asset_market_history","execution_costs"]},
    "volatility": {"name":"Volatility / options risk premia","required":["option_quotes","option_greeks","option_depth"],"downstream":["delta-hedge forward outcomes","gap/vega/gamma calibration"]},
    "event_driven": {"name":"Event-driven alpha","required":["timestamped_events","event_identity"]},
    "microstructure": {"name":"Market microstructure / order-flow alpha","required":["order_book","trade_flow"]},
    "liquidation_distress": {"name":"Liquidation / distress / solver opportunities","required":["liquidation_events","distress_state"],"downstream":["capture-probability calibration","recovery/settlement outcomes"]},
    "capital_location_settlement": {"name":"Capital-location / settlement optionality","required":["venue_opportunity_history","transfer_costs","transfer_latency"]},
}

# A healthy source contributes these evidence classes only; it never grants investment authority.
SOURCES: tuple[dict[str, object], ...] = (
    {"id":"coinbase-market","name":"Coinbase market data","lanes":["price_discrepancy","trend_momentum","mean_reversion","cross_sectional_relative_value"],"classes":["market_quotes","market_history","multi_asset_market_history","execution_costs"],"group":"coinbase","tier":"first_party","provider":["coinbase-exchange:ticker"],"table":("market_quotes","venue","Coinbase")},
    {"id":"bybit-market","name":"Bybit market data","lanes":["price_discrepancy","carry","trend_momentum","mean_reversion","cross_sectional_relative_value"],"classes":["market_quotes","market_history","multi_asset_market_history","execution_costs"],"group":"bybit","tier":"first_party","provider":["bybit-v5:market-snapshot"],"table":("market_quotes","venue","Bybit")},
    {"id":"kraken-market","name":"Kraken market data","lanes":["price_discrepancy","trend_momentum","mean_reversion","cross_sectional_relative_value"],"classes":["market_quotes","market_history","multi_asset_market_history","execution_costs"],"group":"kraken","tier":"first_party","provider":["kraken:PreTrade"],"table":("market_quotes","venue","Kraken")},
    {"id":"okx-market","name":"OKX market data","lanes":["price_discrepancy","carry","trend_momentum","mean_reversion","cross_sectional_relative_value"],"classes":["market_quotes","market_history","multi_asset_market_history","execution_costs"],"group":"okx","tier":"first_party","provider":["okx-v5:market:ticker"],"table":("market_quotes","venue","OKX")},
    {"id":"hyperliquid-market","name":"Hyperliquid market data","lanes":["price_discrepancy","carry","trend_momentum","mean_reversion","cross_sectional_relative_value"],"classes":["market_quotes","market_history","multi_asset_market_history","execution_costs"],"group":"hyperliquid","tier":"first_party","provider":["hyperliquid:metaAndAssetCtxs"],"table":("market_quotes","venue","HlPerp")},
    {"id":"coinbase-l2","name":"Coinbase visible L2","lanes":["price_discrepancy","carry","liquidity_provision","microstructure"],"classes":["executable_depth","order_book"],"group":"coinbase","tier":"first_party","table":("order_books","venue","Coinbase")},
    {"id":"bybit-l2","name":"Bybit visible L2","lanes":["price_discrepancy","carry","liquidity_provision","microstructure"],"classes":["executable_depth","order_book"],"group":"bybit","tier":"first_party","table":("order_books","venue","Bybit")},
    {"id":"okx-l2","name":"OKX visible L2","lanes":["price_discrepancy","carry","liquidity_provision","microstructure"],"classes":["executable_depth","order_book"],"group":"okx","tier":"first_party","table":("order_books","venue","OKX")},
    {"id":"hyperliquid-l2","name":"Hyperliquid visible L2","lanes":["price_discrepancy","carry","liquidity_provision","microstructure"],"classes":["executable_depth","order_book"],"group":"hyperliquid","tier":"first_party","table":("order_books","venue","HlPerp")},
    {"id":"bybit-funding","name":"Bybit funding","lanes":["carry"],"classes":["funding_or_basis"],"group":"bybit","tier":"first_party","provider":["bybit-v5:market-snapshot"],"table":("funding_quotes","venue","Bybit")},
    {"id":"okx-funding","name":"OKX funding","lanes":["carry"],"classes":["funding_or_basis"],"group":"okx","tier":"first_party","provider":["okx-v5:public:funding-rate"],"table":("funding_quotes","venue","OKX")},
    {"id":"hyperliquid-funding","name":"Hyperliquid funding","lanes":["carry"],"classes":["funding_or_basis"],"group":"hyperliquid","tier":"first_party","provider":["hyperliquid:predictedFundings"],"table":("funding_quotes","venue","HlPerp")},
    {"id":"lido-yield","name":"Lido stETH APR","lanes":["yield"],"classes":["yield_rate"],"group":"lido","tier":"protocol_native","provider":["lido:steth-apr-sma"]},
    {"id":"morpho-markets","name":"Morpho markets","lanes":["yield","fundamental_onchain"],"classes":["yield_rate","capacity","exit_liquidity","protocol_fundamentals"],"group":"morpho","tier":"protocol_native"},
    {"id":"aave-liquidations","name":"Aave V3 LiquidationCall logs","lanes":["liquidation_distress"],"classes":["liquidation_events"],"group":"aave","tier":"protocol_native"},
    {"id":"bybit-catalog","name":"Bybit instrument catalog","lanes":["event_driven"],"classes":["timestamped_events","event_identity"],"group":"bybit","tier":"first_party","provider":["bybit-v5:instrument-catalog"]},
    {"id":"coinbase-catalog","name":"Coinbase product catalog","lanes":["event_driven"],"classes":["timestamped_events","event_identity"],"group":"coinbase","tier":"first_party","provider":["coinbase-exchange:product-catalog"]},
    {"id":"snapshot-governance","name":"Snapshot governance","lanes":["event_driven"],"classes":["timestamped_events","event_identity"],"group":"snapshot","tier":"first_party"},
    {"id":"tokenomist-unlocks","name":"Tokenomist unlock calendar","lanes":["event_driven","fundamental_onchain"],"classes":["timestamped_events","event_identity","protocol_fundamentals"],"group":"tokenomist","tier":"secondary","authoritative":False,"credential":"CIE_TOKENOMIST_API_KEY"},
    {"id":"ethereum-publicnode","name":"Ethereum finalized RPC","lanes":["fundamental_onchain"],"classes":["chain_activity"],"group":"ethereum-rpc","tier":"protocol_native","provider":["ethereum-mainnet:publicnode-finalized"]},
    {"id":"defillama-protocols","name":"DefiLlama protocol metrics","lanes":["fundamental_onchain"],"classes":["protocol_fundamentals"],"group":"defillama","tier":"secondary","authoritative":False},
    {"id":"deribit-options","name":"Deribit option books and Greeks","lanes":["volatility"],"classes":["option_quotes","option_greeks","option_depth"],"group":"deribit","tier":"first_party","provider":["deribit:public-option-order-book"]},
    {"id":"bybit-options","name":"Bybit options","lanes":["volatility"],"classes":["option_quotes","option_greeks"],"group":"bybit","tier":"first_party"},
    {"id":"okx-options","name":"OKX options","lanes":["volatility"],"classes":["option_quotes","option_greeks","option_depth"],"group":"okx","tier":"first_party"},
    {"id":"bybit-liquidations","name":"Bybit all-liquidation stream","lanes":["liquidation_distress","microstructure"],"classes":["liquidation_events","liquidation_pressure"],"group":"bybit","tier":"first_party"},
    {"id":"bybit-distress","name":"Bybit ADL / insurance state","lanes":["liquidation_distress"],"classes":["distress_state"],"group":"bybit","tier":"first_party","provider":["bybit-v5:adl-alert","bybit-v5:insurance-pool"]},
    {"id":"hyperliquid-distress","name":"Hyperliquid distress state","lanes":["liquidation_distress"],"classes":["distress_state"],"group":"hyperliquid","tier":"first_party","provider":["hyperliquid:perp-asset-contexts"]},
    {"id":"internal-maker-shadow","name":"Internal maker-fill outcomes","lanes":["liquidity_provision"],"classes":["maker_fill_outcomes"],"group":"internal-maker","tier":"internal","table":("maker_shadow_outcomes",None,None)},
    {"id":"public-trade-flow","name":"Public trade-flow capture","lanes":["liquidity_provision","microstructure"],"classes":["trade_flow"],"group":"trade-flow","tier":"first_party","active":True},
    {"id":"internal-opportunity-history","name":"Durable opportunity history","lanes":["capital_location_settlement"],"classes":["venue_opportunity_history"],"group":"internal-opportunities","tier":"internal","table":("opportunities",None,None)},
    {"id":"internal-transfer-telemetry","name":"Transfer / withdrawal telemetry","lanes":["capital_location_settlement"],"classes":["transfer_costs","transfer_latency"],"group":"internal-transfer","tier":"internal","table":("capital_transfer_outcomes",None,None)},
)